name: Manual Workflow

on:
    workflow_dispatch:


jobs:
  manual-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: First step
      run: |
        echo "Hello From Mamun's Tutorial"
        echo "Welcome to Github Action Class"
    